# https://backstage.io/docs/features/software-catalog/descriptor-format
# TODO move components to their repositories

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public
  description: Public services
spec:
  owner: candradebh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: internal-platform
  description: Internal applications
spec:
  owner: candradebh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infrastructure
  description: Self-hosting
spec:
  owner: candradebh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workstation
  description: Workstation
spec:
  owner: candradebh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tools
  description: tools
spec:
  owner: candradebh
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: https://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
  annotations:
    github.com/project-slug: candradebh/backstage
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  owner: candradebh
  lifecycle: experimental
  system: internal-platform
  dependsOn:
    - component:homelab
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homelab
  description: Self-hosting infrastructure, fully automated from empty disk to operating services.
  links:
    - title: Website
      url: https://homelab.multiversonline.com
    - title: Documentation
      url: https://homelab.multiversonline.com
  annotations:
    github.com/project-slug: candradebh/homelab2026
    backstage.io/techdocs-ref: url:https://github.com/candradebh/homelab2026
spec:
  type: library
  owner: candradebh
  lifecycle: experimental
  system: infrastructure
  dependsOn:
    - component:terraform-cloud
    - component:router
    - component:charts
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: horus
  description: Self-hosting infrastructure, fully automated from empty disk to operating services.
  annotations:
    github.com/project-slug: candradebh/horus
spec:
  type: library
  owner: candradebh
  lifecycle: experimental
  system: infrastructure
  dependsOn:
    - component:terraform-cloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: virtual-networks
  description: Virtual networks based on Zerotier
  annotations:
    github.com/project-slug: candradebh/virtual-networks
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: infrastructure
  dependsOn:
    - component:terraform-cloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: freevpn
  description: Free VPN
  annotations:
    github.com/project-slug: candradebh/freevpn
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: infrastructure
  dependsOn:
    - component:terraform-cloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: router
  description: Router configuration as code
  annotations:
    github.com/project-slug: candradebh/router
spec:
  type: library
  owner: candradebh
  lifecycle: experimental
  system: infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: charts
  description: Helm charts
  annotations:
    github.com/project-slug: candradebh/charts
spec:
  type: library
  owner: candradebh
  lifecycle: experimental
  system: infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-cloud
  description: Terraform Cloud configuration
  annotations:
    github.com/project-slug: candradebh/terraform-cloud
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotfiles
  description: nvim, tmux, zsh, fzf, bspwm, suckless tools, and more!
  annotations:
    github.com/project-slug: candradebh/dotfiles
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: workstation
  dependsOn:
    - component:dmenu
    - component:slock
    - component:st
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: st
  description: Simple terminal
  annotations:
    github.com/project-slug: candradebh/st
spec:
  type: application
  owner: candradebh
  lifecycle: production
  system: workstation
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmenu
  description: Dynamic menu
  annotations:
    github.com/project-slug: candradebh/dmenu
spec:
  type: application
  owner: candradebh
  lifecycle: production
  system: workstation
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slock
  description: Suckless lockscreen
  annotations:
    github.com/project-slug: candradebh/slock
spec:
  type: application
  owner: candradebh
  lifecycle: production
  system: workstation
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workstation-setup
  description: Automated Arch Linux configuration with Ansible 
  annotations:
    github.com/project-slug: candradebh/workstation-setup
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: workstation
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: one-line-firefox
  description: Compact and minimal interface for Firefox 
  annotations:
    github.com/project-slug: candradebh/one-line-firefox
spec:
  type: library
  owner: candradebh
  lifecycle: production
  system: workstation
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: md2pdf
  description: Simple Markdown to PDF converter
  annotations:
    github.com/project-slug: candradebh/one-line-firefox
spec:
  type: application
  owner: candradebh
  lifecycle: production
  system: tools
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blog
  description: Meu blog
  annotations:
    github.com/project-slug: candradebh/blog
spec:
  type: website
  owner: candradebh
  lifecycle: production
  system: public
